### ISSUE TITLE
Individuals peer reviewing their own code

### ISSUE THREAD

**Issue by benwheeler** [ukncsc/secure-development-and-deployment#3]
I disagree that
> individuals can also peer review their own code

If I am attempting to peer review my own code, then I have simply not finished writing and testing my code.

**Comment by toby-ncsc** [comment]
Thanks Ben, we agree. We have made a change [here](https://github.com/ukncsc/secure-development-and-deployment/commit/54fe97d8555b78f15a4f447e9a4b0ebb13fa9ebe
)
