### ISSUE TITLE
Sections 4 and 6 could be merged?

### ISSUE THREAD

**Issue by benwheeler** [ukncsc/secure-development-and-deployment#4]
They are very similar, and to be honest developer machines are effectively a component in the development pipeline anyway (though they are more distributed).

**Comment by llawall** [comment]
I largely agree with this sentiment and the assuming it is not a mistake that 'Actions' and 'Self Assessment' are identical in both sections then it gives more weight to merging the sections too

**Comment by encodedfox** [comment]
I'd agree that they could be merged and just cover that the developer environments are part of the pipeline and need to be secured similarly.

**Comment by toby-ncsc** [comment]
Thank you all for your feedback. Principle 4 and 6 were the same content, which was a mistake during migration of the guidance to github. We have now fixed this [here](https://github.com/ukncsc/secure-development-and-deployment/pull/15)
