### ISSUE TITLE
Ability to react to compromise and/or vulnerability

### ISSUE THREAD

**Issue by benwheeler** [ukncsc/secure-development-and-deployment#5]
While this guidance is explicitly targeted to teams practising continuous delivery, it might be worth noting (maybe in section 8), that you should be able to fix and deploy quickly.

There is no point identifying a problem quickly if it takes you 6 months to get a fix out to Prod.

**Comment by toby-ncsc** [comment]
Thanks Ben, good point. We decided that there are a lot of additional complexities with doing vulnerability management, which make it challenging to address well in this guidance. Time is one of them. We added a link to the NCSC vulnerability management guidance which touches on timescales.  [See here](https://github.com/ukncsc/secure-development-and-deployment/commit/03b23483d6775b1b7f41ffd5db5321c9f4ac373a)
